# Generated by Django 3.2.20 on 2023-08-08 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_blog_tg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='phonenumber',
        ),
    ]
