# Generated by Django 3.2.20 on 2023-08-09 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_user_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MyUser',
        ),
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'MyUser', 'verbose_name_plural': 'MyUsers'},
        ),
    ]
