# Generated by Django 3.2.20 on 2023-08-09 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_alter_post_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='author',
        ),
        migrations.AddField(
            model_name='follow',
            name='blog',
            field=models.ForeignKey(blank=True, help_text='Ссылка на блог пользователя, на который подписываются', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to='news.blog', verbose_name='Блог'),
        ),
    ]
