# Generated by Django 3.2.20 on 2023-08-09 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0016_auto_20230809_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='blog_author',
            field=models.ForeignKey(blank=True, help_text='Ссылка на объект пользователя, на которого подписываются', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='Автор блога'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='blog',
            field=models.ForeignKey(blank=True, help_text='Ссылка на блог пользователя, на который подписываются', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following_blog', to='news.blog', verbose_name='Блог'),
        ),
    ]
