# Generated by Django 3.2.20 on 2023-08-11 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_read_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
